set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports PWM]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCH[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCH[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCH[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCH[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCH[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCH[0]}]
set_property PACKAGE_PIN A15 [get_ports PWM]
set_property PACKAGE_PIN V17 [get_ports {SWITCH[0]}]
set_property PACKAGE_PIN V16 [get_ports {SWITCH[1]}]
set_property PACKAGE_PIN W16 [get_ports {SWITCH[2]}]
set_property PACKAGE_PIN W17 [get_ports {SWITCH[3]}]
set_property PACKAGE_PIN W15 [get_ports {SWITCH[4]}]
set_property PACKAGE_PIN V15 [get_ports {SWITCH[5]}]

set_property PACKAGE_PIN W14 [get_ports {SWITCH[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCH[6]}]

set_property PACKAGE_PIN V17 [get_ports {SFXswitch[0]}]
set_property PACKAGE_PIN V16 [get_ports {SFXswitch[1]}]
set_property PACKAGE_PIN W16 [get_ports {SFXswitch[2]}]
set_property PACKAGE_PIN W17 [get_ports {SFXswitch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFXswitch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFXswitch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFXswitch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFXswitch[0]}]

set_property PACKAGE_PIN U18 [get_ports SFXswitch]
set_property IOSTANDARD LVCMOS33 [get_ports SFXswitch]
