set_property IOSTANDARD LVCMOS33 [get_ports red]
set_property IOSTANDARD LVCMOS33 [get_ports green]
set_property IOSTANDARD LVCMOS33 [get_ports blue]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports BOOSTButton]

set_property IOSTANDARD LVCMOS33 [get_ports locked]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property IOSTANDARD LVCMOS33 [get_ports Debug]

set_property PACKAGE_PIN G19 [get_ports red[3]]
set_property PACKAGE_PIN H19 [get_ports red[2]]
set_property PACKAGE_PIN J19 [get_ports red[1]]
set_property PACKAGE_PIN N19 [get_ports red[0]]
set_property PACKAGE_PIN J17 [get_ports green[3]]
set_property PACKAGE_PIN H17 [get_ports green[2]]
set_property PACKAGE_PIN G17 [get_ports green[1]]
set_property PACKAGE_PIN D17 [get_ports green[0]]
set_property PACKAGE_PIN N18 [get_ports blue[3]]
set_property PACKAGE_PIN L18 [get_ports blue[2]]
set_property PACKAGE_PIN K18 [get_ports blue[1]]
set_property PACKAGE_PIN J18 [get_ports blue[0]]

set_property PACKAGE_PIN U17 [get_ports reset]
set_property PACKAGE_PIN W5 [get_ports clk_100MHz]
set_property PACKAGE_PIN U18 [get_ports BOOSTButton]

set_property PACKAGE_PIN L1 [get_ports locked]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]


set_property PACKAGE_PIN U16 [get_ports Debug[0]]
set_property PACKAGE_PIN E19 [get_ports Debug[1]]
set_property PACKAGE_PIN U19 [get_ports Debug[2]]
set_property PACKAGE_PIN V19 [get_ports Debug[3]]
set_property PACKAGE_PIN W18 [get_ports Debug[4]]
set_property PACKAGE_PIN U15 [get_ports Debug[5]]
set_property PACKAGE_PIN U14 [get_ports Debug[6]]
set_property PACKAGE_PIN V14 [get_ports Debug[7]]
set_property PACKAGE_PIN V3  [get_ports Debug[8]]
set_property PACKAGE_PIN W3  [get_ports Debug[9]]